services:
  - type: web
    name: nme-encradant
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: TOKEN
        sync: false
      - key: PORT
        value: 10000

